// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekxgbmfaxkduwvrpunja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVreGdibWZheGtkdXd2cnB1bmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTIxMjksImV4cCI6MjA2MDEyODEyOX0.f2wTI5Nxjc85TjCTiBYPBInmM9F9n2442a8k_lkvs7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);